PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?uLabel ?founded ?stateLabel ?stateStart
 WHERE {
   ?u wdt:P31|wdt:P279/wdt:P31 wd:Q3918 .
   ?u wdt:P131+ ?state .
   ?state wdt:P31 wd:Q35657 .
   ?state wdt:P571 ?stateStart .
   ?u wdt:P571 ?founded .
   FILTER (?founded < ?stateStart) .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
   }
 }
 LIMIT 10