PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?entity ?claim ?prop WHERE {
  ?prop wdt:P31 wd:Q18615033 .
  ?prop wikibase:reference ?propClaim .
  ?ref ?propClaim ?o .
  ?statement prov:wasDerivedFrom ?ref .
  ?entity ?claim ?statement .
  } LIMIT 100