PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?discoverer ?name (COUNT(?asteroid) AS ?count)
 WHERE {
   ?asteroid wdt:P31 wd:Q3863 .
   ?asteroid wdt:P61 ?discoverer .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?discoverer rdfs:label ?name
   }
 }
 GROUP BY ?discoverer ?name
 ORDER BY DESC(?count)
 LIMIT 10